auth:
  password: qwerty63
  username: admin
endpoints:
  five_sec: http://185.5.248.212:8252/logs/predictions_dev2.table
  minute_hour: http://185.5.248.212:8150/logs/predictions_dev.table
entry_threshold: 3.0e-05
exit_threshold: 3.0e-05
fee_pct: 7.5e-06
mae_stop_enabled: true
mae_stop_threshold: 12.0
stop_loss_pct: 0.01
poll_intervals:
  1h: 60
  1m: 10
  5s: 5
start_balance: 1000
ui:
  default_interval: 5s
  logs_interval: 5s
  logs_page_size: 100
env: dev2
ports:
  prod:
    simulation: 8060
    logs: 8061
    session_manager: 8062
  dev:
    simulation: 8160
    logs: 8161
    session_manager: 8162
  dev2:
    simulation: 8260
    logs: 8261
    session_manager: 8262
